micronaut:
  application:
    name: bank-accounts
  server:
    port: 8090

datasources:
  default:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driverClassName: ${database.driver:com.mysql.cj.jdbc.Driver}

flyway:
  datasources:
    default:
      enabled: true

jpa:
  default:
    entity-scan:
      packages: 'com.blitzar.bank.accounts.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
      show-sql: true

jackson:
  mapper:
    accept-case-insensitive-enums: true
    accept-single-value-as-array: true