### Bank Account Application (rest api -> Amazon SQS)
POST http://localhost:8090/api/v1/bank-accounts/application
Content-Type: application/json

{
  "accountHolders": [
    {"accountHolderName":"Test Account Holder #1", "dateOfBirth":"1992-06-24"},
    {"accountHolderName":"Test Account Holder #2", "dateOfBirth":"2015-07-14"}
  ]
}